### ISSUE TITLE
Errors with multiplications

### ISSUE THREAD

**Issue by lujonathanh** [dawenl/stochastic_PMF#1] opened 2016-04-10 00:30 UTC
Hello,

When I try to call PoissonMF.fit, I get an error in the dot products. In particular, for the _gamma_term function, I get:

ValueError: shapes (1000,20) and (1,20) not aligned: 20 (dim 1) != 1 (dim 0)

return np.sum((a - shape) \* Elogx - (b - rate) \* Ex +
    #              (special.gammaln(shape) - shape \* np.log(rate)))

I was wondering if you could tell me which term the _gamma_term refers to in the paper http://dawenl.github.io/publications/LiangPE14-codebook.pdf. _gamma_term seems to be calculated in the estimated log likelihood. Could you point me to an explicit definition of the _gamma_term?

**Comment by dawenl** [comment] 2016-04-10 02:08
It's the gamma log-likelihood which appears in the objective (but not explicitly in the paper). 

It looks like the parameter you passed in has some unexpected shape. Can you provide a small example of your input so that I can have a better idea of what might go wrong?

**Comment by lujonathanh** [comment] 2016-04-10 13:52
Thank you for your response!

My input X is a 1000 by 5000 sparse matrix, and I am calling with num_components = 20.
I think the error is thrown by shape \* np.log(rate), since shape has dimensions  (1000,20) and rate has dimensions (1,20).

After replacing all instances of two matrices being multiplied together, from \* to np.multiply, I think the code is working. For some reason on my machine numpy's default seems to be to run np.dot (i.e. take the matrix product) instead of np.multiply.

When running with verbose output, I get output in the form:
"After ITERATION: 19    Objective: 58314830.55  Old objective: 58287326.89  Improvement: 0.00047"

The objectives are monotonically increasing with each iteration. This is expected, right?
Are these typical numbers for the code's output?

One last question: could you comment on whether I am using the code correctly? I am applying pmf to factorize a bitcoin transaction matrix, where the rows are unique senders, the columns are unique receivers, and each entry represents the number of transactions (the idea is to predict most likely later transactions). Do you think the model could still be useful in this case?

Thank you very much for your response and help!

**Comment by dawenl** [comment] 2016-04-10 22:44
Is your input an instance of `scipy.sparse.csr_matrix` (or some other sparse matrix format)? If so, that is the problem. This code expects input to be `numpy.ndarray`. The problem is that `*` means completely different things for `csr_matrx` and `ndarray`: for former, it means matrix multiplication, while for the latter, it means element-wise multiplication. And there are many other subtle differences that could potentially break the code. It looks like you've pin-pointed a few places to make the change, but I would recommend passing `X.toarray()` (assuming your input matrix is `X`) since it's only 1000 by 5000. 

I also have similar PMF code which takes a sparse matrix as input, but it is currently not public yet... 

The objective should monotonically increase, so that is good -- the value itself is problem- and data-specific, so I cannot really tell you if it makes sense or not. 

Regarding your application, it indeed sounds like something matrix factorization could be useful. You might also want to take a look at Gaussian matrix factorization where the factors are not constrained to be non-negative.

**Comment by dawenl** [comment] 2016-04-12 13:07
Looks like your problem is solved. I will close the issue for now, but feel free to reopen it.

**Closed as completed by dawenl** 2016-04-12 13:07 UTC

**Comment by lujonathanh** [comment] 2016-04-12 15:42
Indeed it is. Thank you so much for your response and clarifications!
